server:
  port: 9000  # 9000번 포트로 실행
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-sy.cnkf7vpmvx5v.ap-northeast-2.rds.amazonaws.com/bunjang
    username: sy
    password: test0529
    driver-class-name: com.mysql.cj.jdbc.Driver
